#!/usr/bin/env python3
"""
Magnifica Humanitas 뷰어 데이터 빌드 스크립트

chapters_en/ 와 chapters_ko/ 의 마크다운을 읽어
magnifica_data.js 단일 자산으로 합친다. magnifica.html이 로드한다.
"""
from __future__ import annotations
import json
import re
from pathlib import Path

ROOT = Path(__file__).parent
BASE = ROOT / "교단별 AI 가이드라인" / "29_가톨릭_레오14세_MagnificaHumanitas회칙_2026"
EN_DIR = BASE / "chapters_en"
KO_DIR = BASE / "chapters_ko"

CHAPTER_ORDER = [
    ("00_introduction", "서론", "Introduction"),
    ("01_chapter_one", "1장 — 복음에 충실한 역동적 접근", "Chapter One — A Dynamic Approach Faithful to the Gospel"),
    ("02_chapter_two", "2장 — 교회 사회 교리의 기초와 원리", "Chapter Two — Foundations and Principles of the Social Doctrine of the Church"),
    ("03_chapter_three", "3장 — 기술과 지배: 인공지능 시대 인간의 위대함", "Chapter Three — Technology and Dominion; The Greatness of the Human Person in the Time of AI"),
    ("04_chapter_four", "4장 — 변혁의 시대에 인간을 수호함: 진리·노동·자유", "Chapter Four — Safeguarding the Human Person in a Time of Transformation: Truth, Labour and Freedom"),
    ("05_chapter_five", "5장 — 권력의 문화와 사랑의 문명", "Chapter Five — The Culture of Power and the Civilization of Love"),
    ("06_conclusion", "결론", "Conclusion"),
    ("07_footnotes", "각주", "Footnotes"),
]


def read_or_placeholder(path: Path, label: str) -> str:
    if path.exists():
        return path.read_text(encoding="utf-8")
    return f"_({label} 번역 진행 중 — 잠시 후 다시 방문해 주세요.)_"


def main():
    meta = {
        "titleKo": "위대한 인간성",
        "titleLatin": "Magnifica Humanitas",
        "subtitleKo": "인공지능 시대에 인격을 수호함에 관한 회칙",
        "subtitleEn": "On Safeguarding the Human Person in the Time of Artificial Intelligence",
        "author": "레오 14세 교황 (Pope Leo XIV)",
        "signedDate": "2026년 5월 15일 — 레오 13세 「새로운 사태」 반포 135주년",
        "promulgatedDate": "2026년 5월 25일",
        "docType": "회칙 (Encyclical Letter)",
        "language": "다국어 동시 발표 (한국어 번역본)",
        "officialUrl": "https://www.vatican.va/content/leo-xiv/en/encyclicals/documents/20260515-magnifica-humanitas.html",
        "wordCountEn": 40409,
    }

    chapters = []
    for slug, title_ko, title_en in CHAPTER_ORDER:
        en = read_or_placeholder(EN_DIR / f"{slug}.md", title_en)
        ko = read_or_placeholder(KO_DIR / f"{slug}.md", title_ko)
        chapters.append({
            "id": slug,
            "titleKo": title_ko,
            "titleEn": title_en,
            "contentKo": ko,
            "contentEn": en,
        })

    out = ROOT / "magnifica_data.js"
    payload = json.dumps({"meta": meta, "chapters": chapters}, ensure_ascii=False, indent=2)
    out.write_text(
        f"// AUTO-GENERATED by build_magnifica.py — do not edit by hand.\n"
        f"window.MAGNIFICA = {payload};\n",
        encoding="utf-8",
    )

    print(f"✅ magnifica_data.js ({out.stat().st_size // 1024} KB)")
    for ch in chapters:
        ko_chars = len(ch["contentKo"])
        en_chars = len(ch["contentEn"])
        status = "✓" if ko_chars > 200 else "⏳"
        print(f"  {status} {ch['id']}: EN {en_chars:,} chars · KO {ko_chars:,} chars")


if __name__ == "__main__":
    main()
